/* 1-1 */
SELECT DEPTNO
	, ROUND(AVG(SAL), 0) AS avg_sal
	, MAX(SAL) AS max_sal
	, MIN(SAL) AS min_sal
	, COUNT(EMPNO) AS cnt
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO DESC
;


/* 1-2 */
SELECT JOB
	, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3
ORDER BY COUNT(*) DESC
;


/* 1-3 */
SELECT EXTRACT(YEAR FROM HIREDATE) AS hire_year
	, DEPTNO
	, COUNT(*) AS cnt
FROM EMP
GROUP BY EXTRACT(YEAR FROM HIREDATE), DEPTNO
ORDER BY HIRE_YEAR DESC, DEPTNO ASC
;


/* 1-4 */
SELECT NVL2(COMM, 'Y', 'N') AS exist_comm
	, COUNT(*) AS cnt
FROM EMP
GROUP BY NVL2(COMM, 'Y', 'N')
ORDER BY cnt ASC
;


/* 1-5 */
SELECT DEPTNO
	, EXTRACT(YEAR FROM HIREDATE) AS hire_year
	, COUNT(*) AS cnt
	, MAX(SAL)
	, SUM(SAL)
	, AVG(SAL)
FROM EMP
GROUP BY CUBE(DEPTNO, EXTRACT(YEAR FROM HIREDATE))
ORDER BY DEPTNO, HIRE_YEAR
;


/* 2-1 (1) */
SELECT d.DEPTNO
    , d.DNAME
    , e.EMPNO
    , e.ENAME
    , e.SAL
FROM EMP e, DEPT d
WHERE e.DEPTNO = d.DEPTNO AND e.SAL > 2000
ORDER BY d.DEPTNO, e.JOB ASC
;


/* 2-1 (2) */
SELECT d.DEPTNO
    , d.DNAME
    , e.EMPNO
    , e.ENAME
    , e.SAL
FROM EMP e JOIN DEPT d ON (e.DEPTNO = d.DEPTNO AND e.SAL > 2000)
ORDER BY d.DEPTNO, e.JOB ASC
;



/* 2-2 */
SELECT e.DEPTNO
    , d.DNAME
    , FLOOR(AVG(e.SAL)) AS avg_sal
    , MAX(e.SAL) AS max_sal
    , MIN(e.SAL) AS min_sal
    , COUNT(e.DEPTNO) AS cnt
FROM EMP e JOIN DEPT d ON e.DEPTNO = d.DEPTNO
GROUP BY e.DEPTNO, d.DNAME
ORDER BY e.DEPTNO, d.DNAME
;



/* 2-3 */
SELECT d.DEPTNO
    , d.DNAME
    , e.EMPNO
    , e.ENAME
    , e.JOB
    , e.SAL
FROM EMP e RIGHT OUTER JOIN DEPT d ON (e.DEPTNO = d.DEPTNO)
ORDER BY d.DEPTNO, d.DNAME;
;



/* 2-4 */
SELECT d.DEPTNO AS deptno
    , d.DNAME
    , e.EMPNO
    , e.ENAME
    , e.MGR
    , e.SAL
    , e.DEPTNO AS deptno
    , s.LOSAL
    , s.HISAL
    , s.GRADE
    , e2.EMPNO AS mgr_empno
    , e2.ENAME AS mgr_ename
FROM EMP e RIGHT JOIN DEPT d ON (e.DEPTNO = d.DEPTNO)
LEFT OUTER JOIN SALGRADE s ON (e.SAL >= s.LOSAL AND e.SAL <= s.HISAL)
LEFT OUTER JOIN EMP e2 ON (e.MGR = e2.EMPNO)
ORDER BY d.DEPTNO, e.EMPNO


/* 210p (1) */
SELECT e.JOB
	, e.EMPNO
	, e.ENAME
	, e.SAL
	, e.DEPTNO
	, d.DNAME
FROM EMP e, DEPT d
WHERE e.JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN')
	AND e.DEPTNO = d.DEPTNO
ORDER BY sal DESC
;


/* 210p (2) */
SELECT e.EMPNO
    , e.ENAME
    , d.DNAME
    , e.HIREDATE
    , d.LOC
    , e.SAL
    , s.GRADE
FROM EMP E LEFT JOIN DEPT d ON (e.DEPTNO = d.DEPTNO)
INNER JOIN SALGRADE s ON (e.SAL >= s.LOSAL AND e.SAL <= s.HISAL)
AND e.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY SAL DESC, EMPNO ASC
;


/* 211p (3) */
SELECT e.EMPNO
    , e.ENAME
    , e.JOB
    , e.DEPTNO
    , d.DNAME
    , d.LOC
FROM EMP e, DEPT d
WHERE e.ENAME IN (SELECT ENAME FROM EMP WHERE DEPTNO = '10')
	AND e.JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO = '30')
	AND e.DEPTNO = d.DEPTNO
;


/* 211p (4) */
SELECT e.EMPNO
    , e.ENAME
	, e.SAL
	, s.GRADE
FROM EMP e, SALGRADE s 
WHERE e.SAL BETWEEN s.LOSAL AND s.HISAL 
	AND e.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN')
ORDER BY EMPNO ASC
;


/* 211p (5) */
SELECT e.EMPNO
    , e.ENAME
    , e.SAL
    , s.GRADE
FROM EMP e, SALGRADE s
WHERE e.SAL BETWEEN s.LOSAL AND s.HISAL
	AND e.SAL > ALL (SELECT SAL FROM EMP WHERE JOB = 'SALESMAN')
ORDER BY EMPNO ASC
;